### ISSUE TITLE
"NAN"  to invalid json

### ISSUE THREAD

**Issue by SalikovAlex** [sanand0/xmljson#23]
```
>>> from lxml import etree
>>> from xmljson import XMLData
>>> XMLData(attr_prefix=None, dict_type=dict).data(etree.XML('<ROOT test="NAN"/>'))
{'ROOT': {'test': nan}}
```

**Comment by SalikovAlex** [comment]
because 
```
>>> float('nan')
nan
>>> float('inf')
inf
>>> float('-inf')
-inf
```

**Comment by sanand0** [comment]
@Sasha4ever - thanks. This raises a broader question:

- Should `1E6` be converted to a float or not? It's possible that it is an ID
- Should `true` always be converted to boolean?
- Should we allow `True` to also represent a boolean?

Because of the variety of possible conversions, you can pass an `xml_fromstring` that uses the conversion method you prefer. For example:

```python
>>> from lxml import etree
>>> from xmljson import XMLData
>>> XMLData(xml_fromstring=str, attr_prefix=None, dict_type=dict).data(etree.XML('<ROOT test="NAN"/>'))
{'ROOT': {'test': 'NAN'}}
```

Hope that resolves the issue.

**Comment by SalikovAlex** [comment]
IMHO XMLData shouldn't return invalid XML.

**Comment by dagwieers** [comment]
@Sasha4ever I don't see from your comments that XMLData is returning invalid XML. Can you elaborate ?

Ah, I think you mean return invalid JSON. Yes, that requires a fix.

The question is what would you like for these values in the resulting JSON output. To me it's unclear whether we want to fail the conversion, make it null or keep it as a string. Any insight you want to share ?
